# Configuration inspired by Ricardo Mendes
# Original repository: ricardolsmendes/gcp-cloudbuild-gae-angular

runtime: python27
api_version: 1
threadsafe: yes

# Google App Engine's cache default expiration time is 10 minutes. It's suitable for most Production
# scenarios, but a shorter TTL may be desired for Development and QA, as it allows us to see a fresh
# code in action just a minute after the deployment.
default_expiration: 60s

handlers:

  - url: /.*
    static_files: dist/ProvrWebsite/index.html
    upload: dist/ProvrWebsite/index.html
  - url: /
    static_dir: dist/ProvrWebsite

skip_files:
  - e2e/
  # - ^(?!dist)
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
