# Configuration inspired by Ricardo Mendes
# Original repository: ricardolsmendes/gcp-cloudbuild-gae-angular

runtime: python27
api_version: 1
threadsafe: yes

# Google App Engine's cache default expiration time is 10 minutes. It's suitable for most Production
# scenarios, but a shorter TTL may be desired for Development and QA, as it allows us to see a fresh
# code in action just a minute after the deployment.
# default_expiration: 60s

handlers:
  - url: /(.+\.js)
    static_files: dist/ProvrWebsite/src/\1
    upload: dist/ProvrWebsite/src/(.+\.js)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.css)
    static_files: dist/ProvrWebsite/src/\1
    upload: dist/ProvrWebsite/src/(.+\.css)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.png)
    static_files: dist/ProvrWebsite/src/\1
    upload: dist/ProvrWebsite/src/(.+\.png)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.jpg)
    static_files: dist/ProvrWebsite/src/\1
    upload: dist/ProvrWebsite/src/(.+\.jpg)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.gif)
    static_files: dist/ProvrWebsite/src/\1
    upload: dist/ProvrWebsite/src/(.+\.gif)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.svg)
    static_files: dist/ProvrWebsite/src/\1
    upload: dist/ProvrWebsite/src/(.+\.svg)
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.ico
    static_files: dist/ProvrWebsite/src/favicon.ico
    upload: dist/ProvrWebsite/src/favicon.ico
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.json)
    static_files: dist/ProvrWebsite/src/\1
    upload: dist/ProvrWebsite/src/(.+\.json)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+)
    static_files: dist/ProvrWebsite/src/index.html
    upload: dist/ProvrWebsite/src/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_files: dist/ProvrWebsite/src/index.html
    upload: dist/ProvrWebsite/src/index.html
    secure: always
    redirect_http_response_code: 301

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
